$image = /home/ale/Pictures/Wallpapers/a_sunset_over_a_body_of_water_with_Marfa_lights_in_the_background.png

$background = rgba(171216ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(352f34ff)

$inverse_primary = rgba(7c4e7eff)

$inverse_surface = rgba(ebdfe6ff)

$on_background = rgba(ebdfe6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(49204dff)

$on_primary_container = rgba(ffd6fcff)

$on_primary_fixed = rgba(320936ff)

$on_primary_fixed_variant = rgba(623765ff)

$on_secondary = rgba(3c2b3bff)

$on_secondary_container = rgba(f5dbf1ff)

$on_secondary_fixed = rgba(251626ff)

$on_secondary_fixed_variant = rgba(534152ff)

$on_surface = rgba(ebdfe6ff)

$on_surface_variant = rgba(d0c3ccff)

$on_tertiary = rgba(4c251eff)

$on_tertiary_container = rgba(ffdad3ff)

$on_tertiary_fixed = rgba(33110bff)

$on_tertiary_fixed_variant = rgba(673b33ff)

$outline = rgba(998d96ff)

$outline_variant = rgba(4d444cff)

$primary = rgba(edb4ebff)

$primary_container = rgba(623765ff)

$primary_fixed = rgba(ffd6fcff)

$primary_fixed_dim = rgba(edb4ebff)

$scrim = rgba(000000ff)

$secondary = rgba(d8bfd4ff)

$secondary_container = rgba(534152ff)

$secondary_fixed = rgba(f5dbf1ff)

$secondary_fixed_dim = rgba(d8bfd4ff)

$shadow = rgba(000000ff)

$source_color = rgba(3d323cff)

$surface = rgba(171216ff)

$surface_bright = rgba(3e373cff)

$surface_container = rgba(241e23ff)

$surface_container_high = rgba(2e282dff)

$surface_container_highest = rgba(393338ff)

$surface_container_low = rgba(1f1a1fff)

$surface_container_lowest = rgba(120d11ff)

$surface_dim = rgba(171216ff)

$surface_tint = rgba(edb4ebff)

$surface_variant = rgba(4d444cff)

$tertiary = rgba(f6b8acff)

$tertiary_container = rgba(673b33ff)

$tertiary_fixed = rgba(ffdad3ff)

$tertiary_fixed_dim = rgba(f6b8acff)

