$image = /home/ale/Pictures/Wallpapers/wallhaven-jxolqq_1920x1080.png

$background = rgba(151218ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(332f35ff)

$inverse_primary = rgba(6e528bff)

$inverse_surface = rgba(e8e0e8ff)

$on_background = rgba(e8e0e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3e2459ff)

$on_primary_container = rgba(efdbffff)

$on_primary_fixed = rgba(280d43ff)

$on_primary_fixed_variant = rgba(553b71ff)

$on_secondary = rgba(362d3fff)

$on_secondary_container = rgba(edddf6ff)

$on_secondary_fixed = rgba(21182aff)

$on_secondary_fixed_variant = rgba(4d4357ff)

$on_surface = rgba(e8e0e8ff)

$on_surface_variant = rgba(ccc4cfff)

$on_tertiary = rgba(4b252bff)

$on_tertiary_container = rgba(ffd9ddff)

$on_tertiary_fixed = rgba(321017ff)

$on_tertiary_fixed_variant = rgba(653a41ff)

$outline = rgba(968e98ff)

$outline_variant = rgba(4a454eff)

$primary = rgba(dabaf9ff)

$primary_container = rgba(553b71ff)

$primary_fixed = rgba(efdbffff)

$primary_fixed_dim = rgba(dabaf9ff)

$scrim = rgba(000000ff)

$secondary = rgba(d0c1daff)

$secondary_container = rgba(4d4357ff)

$secondary_fixed = rgba(edddf6ff)

$secondary_fixed_dim = rgba(d0c1daff)

$shadow = rgba(000000ff)

$source_color = rgba(725195ff)

$surface = rgba(151218ff)

$surface_bright = rgba(3c383eff)

$surface_container = rgba(221e24ff)

$surface_container_high = rgba(2c292eff)

$surface_container_highest = rgba(373339ff)

$surface_container_low = rgba(1e1a20ff)

$surface_container_lowest = rgba(100d12ff)

$surface_dim = rgba(151218ff)

$surface_tint = rgba(dabaf9ff)

$surface_variant = rgba(4a454eff)

$tertiary = rgba(f3b7beff)

$tertiary_container = rgba(653a41ff)

$tertiary_fixed = rgba(ffd9ddff)

$tertiary_fixed_dim = rgba(f3b7beff)

