cursor            #e2b7f4
cursor_text_color #432254

foreground            #e9e0e7
background            #110d12
selection_foreground  #392c3e
selection_background  #d4c0d8
url_color             #d4c0d8

#: black 000000 767676
color0  #161217
color8  #383339
#: red cc0403 f2201f
color1  #619999
color9  #bdd6d6
#: green 19cb00 23fd00
color2  #d4c0d8
color10 #f0dcf4
#: yellow cecb00 fffd00
color3  #f5b7b6
color11 #ffdad9
#: blue 0d73cc 1a8fff
color4  #5b396c
color12 #e2b7f4
#: magenta cb1ed1 fd28ff
color5  #504255
color13 #d4c0d8
#: cyan 0dcdcd 14ffff
color6  #663b3b
color14 #f5b7b6
#: white dddddd ffffff
color7  #cec3ce
color15 #e9e0e7

mark1_foreground #2c0b3e
mark1_background #f6d9ff
mark2_foreground #231728
mark2_background #f0dcf4
mark3_foreground #331112
mark3_background #ffdad9

active_tab_foreground #432254
active_tab_background #e2b7f4
inactive_tab_foreground #f6d9ff
inactive_tab_background #5b396c

active_border_color #e2b7f4
inactive_border_color #432254
# bell_border_color #ff5a00
