cursor            #dabaf9
cursor_text_color #3e2459

foreground            #e8e0e8
background            #100d12
selection_foreground  #362d3f
selection_background  #d0c1da
url_color             #d0c1da

#: black 000000 767676
color0  #151218
color8  #373339
#: red cc0403 f2201f
color1  #4d582f
color9  #9fb16f
#: green 19cb00 23fd00
color2  #d0c1da
color10 #edddf6
#: yellow cecb00 fffd00
color3  #f3b7be
color11 #ffd9dd
#: blue 0d73cc 1a8fff
color4  #553b71
color12 #dabaf9
#: magenta cb1ed1 fd28ff
color5  #4d4357
color13 #d0c1da
#: cyan 0dcdcd 14ffff
color6  #653a41
color14 #f3b7be
#: white dddddd ffffff
color7  #ccc4cf
color15 #e8e0e8

mark1_foreground #280d43
mark1_background #efdbff
mark2_foreground #21182a
mark2_background #edddf6
mark3_foreground #321017
mark3_background #ffd9dd

active_tab_foreground #3e2459
active_tab_background #dabaf9
inactive_tab_foreground #efdbff
inactive_tab_background #553b71

active_border_color #dabaf9
inactive_border_color #3e2459
# bell_border_color #ff5a00
